### ISSUE TITLE
User.GetFriends xml conflict

### ISSUE THREAD

**Issue by ozankasikci** [shkh/lastfm-go#9]
Trying to fetch user's friends give the following error:
`field "Image" with tag "image" conflicts with field "Images" with tag "image"`

Editing UserGetFriends struct solved the problem for me. This should be fixed i guess?

Thanks.

**Comment by shkh** [comment]
Thanks! You are right.
I fixed this bug. 30efe775cb404f6895a70d569977804fe4e966e7
